### ISSUE TITLE
key for https://cineb.rs/

### ISSUE THREAD

**Issue by Sofie99** [enimax-anime/key#2]
The site is similar with flixhq.
it uses megacloud but when i use e6/e4/e0 key doesn't work
@enimax-anime

**Comment by enimax-anime** [comment]
Megacloud uses e6, I'm pretty sure.

**Comment by Gujal00** [comment]
e6 key works fine with e1 megacloud embeds

**Comment by enimax-anime** [comment]
Apparently e1 has a different key. Although I would need to work on making my extractor work for e1.

**Comment by enimax-anime** [comment]
Added: https://raw.githubusercontent.com/enimax-anime/key/e1/key.txt
It might still be unstable though
