### ISSUE TITLE
rabbitstream

### ISSUE THREAD

**Issue by XanXus96** [enimax-anime/key#3]
is this key made for rabitstream? because i've tried it and it doesn't work for it

**Comment by enimax-anime** [comment]
What branch are you using?

**Comment by XanXus96** [comment]
e6

**Comment by enimax-anime** [comment]
Try using e4. That's where rabbitstream's key is.

**Comment by XanXus96** [comment]
ok so i guess e4 is for /embed-4/ thanks

**Comment by enimax-anime** [comment]
Indeed
